# Generated by Django 4.2.13 on 2024-08-04 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Session_Year_id',
            new_name='session_year',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
