# Generated by Django 4.2.14 on 2024-08-29 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_auto_update_models'),
        ('myapp', '0002_rename_course_id_student_course_and_more'),
    ]

    operations = [
    ]
